name: Publish npm package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@pointer0592'
      - run: yarn
      - run: yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ESLINT_CONFIG_TOKEN }}
